export const rooms = [
    {
        slug: 'courtyard-room',
        code: 'RM-01',
        name: 'The Courtyard Room',
        description: 'Garden-facing with a queen bed and soft morning light.',
        size: '22m²',
        guests: 2,
        price: 45000,
        image: '/images/courtyard.webp',
        status: 'available',
    },
    {
        slug: 'terrace-suite',
        code: 'RM-02',
        name: 'The Terrace Suite',
        description: 'A private balcony over the courtyard, king bed, sitting area.',
        size: '34m²',
        guests: 3,
        price: 78000,
        image: '/images/terrace.webp',
        status: 'low',
    },
    {
        slug: 'study-room',
        code: 'RM-03',
        name: 'The Study Room',
        description: 'Compact and quiet, with a proper desk for working travelers.',
        size: '18m²',
        guests: 1,
        price: 32000,
        image: '/images/studyroom.webp',
        status: 'booked',
    },
    {
        slug: 'the-loft',
        code: 'RM-04',
        name: 'The Loft',
        description: 'A mezzanine level suite with king bed and skylight.',
        size: '40m²',
        guests: 3,
        price: 95000,
        image: '/images/loftroom.webp',
        status: 'available',
    },
    {
        slug: 'garden-double',
        code: 'RM-05',
        name: 'Garden Double',
        description: 'Two double beds opening onto the garden, ideal for friends or family.',
        size: '28m²',
        guests: 4,
        price: 58000,
        image: '/images/double.webp',
        status: 'available',
    },
    {
        slug: 'executive-suite',
        code: 'RM-06',
        name: 'Executive Suite',
        description: 'A separate sitting area and work desk, for longer stays or business travel.',
        size: '46m²',
        guests: 2,
        price: 110000,
        image: '/images/executive.webp',
        status: 'low',
    },
    {
        slug: 'poolside-room',
        code: 'RM-07',
        name: 'Poolside Room',
        description: 'Ground floor, steps from the pool, with a private outdoor sitting nook.',
        size: '26m²',
        guests: 2,
        price: 52000,
        image: '/images/poolroom.webp',
        status: 'available',
    },
    {
        slug: 'penthouse-suite',
        code: 'RM-08',
        name: 'Penthouse Suite',
        description: 'The top-floor suite, with a wraparound balcony and city views.',
        size: '58m²',
        guests: 4,
        price: 145000,
        image: '/images/penthouse.webp',
        status: 'booked',
    },
    {
        slug: 'family-suite',
        code: 'RM-09',
        name: 'Family Suite',
        description: 'Two connecting bedrooms with a shared living area, built for families or small groups traveling together.',
        size: '52m²',
        guests: 5,
        price: 128000,
        image: '/images/familyroom.webp',
        status: 'available',
    },
];